name: "{{ project-name }}-dev"

services:
  postgres:
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres-vol:/var/lib/postgresql/data/
    env_file: [ galvyn.env ]
    build:
      dockerfile: ./build/dockerfiles/postgres.Dockerfile

  frontend:
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    env_file: [ galvyn.env ]
    user: "${UID}:${GID}"
    build:
      dockerfile: ./build/dockerfiles/frontend-dev.Dockerfile

  webserver:
    labels:
      - webserver
    restart: unless-stopped
    depends_on: [ postgres ]
    stop_signal: SIGTERM
    volumes:
      - ./webserver/migrations:/migrations
    env_file: [ galvyn.env ]
    environment:
      - RUST_LOG=${RUST_LOG-info,webserver=debug}
    user: "${UID}:${GID}"
    build:
      dockerfile: ./build/dockerfiles/webserver-dev.Dockerfile

  nginx:
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on: [ webserver, frontend ]
    env_file: [ galvyn.env ]
    volumes:
      - ./data/conf/nginx-dev/nginx.conf:/etc/nginx/conf.d/default.conf
    build:
      dockerfile: ./build/dockerfiles/nginx-dev.Dockerfile

volumes:
  postgres-vol:
    name: ${COMPOSE_PROJECT_NAME}-postgres-vol-${DEV_TAG}
